#!/usr/bin/env python2.7
#encoding: utf-8
""" Ui launching, main script """
# Gtk and twisted imports


from twisted.internet import gireactor
gireactor.install(useGtk = True)
from twisted.internet import reactor

import logging
from app.main_app import App		


def main():
	""" Main function for script """
	app = App()
	logging.debug("App constructed {}".format(app))
	reactor.run()#pylint: disable = E1101

if __name__ == "__main__":
	main()
