#!/usr/bin/env python2.7
#encoding: utf-8
""" Ui launching, main script """
# Gtk and twisted imports

from twisted.internet import gireactor
gireactor.install(useGtk = True)

from twisted.internet import reactor

#################
from optparse import OptionParser
parser = OptionParser()
parser.add_option("-D", "--debug", dest = 'debug', default = False, \
		help = "put logging in debug verbosity")
(options, args) = parser.parse_args()
################


import logging
if options.debug:
	logging.basicConfig(level=logging.DEBUG)


from snakeguice import Injector

from app.main_app import AppModule, App	


def main():
	""" Main function for script """
	injector = Injector(AppModule())
	app = injector.get_instance(App)
	logging.debug("App constructed {}".format(app))
	reactor.run()#pylint: disable = E1101

if __name__ == "__main__":
	main()
