#!/bin/sh

function write_conf_var(){
	var_name=$1
	conf_file=$2
	if [[  -f "$conf_file" ]] &&  grep "^$var_name=" "$conf_file" 2>&1 >/dev/null ; then 
		sed -i "s#$var_name=\(.*\)#$var_name=\"$(eval echo \$$var_name)\"#g" $conf_file
	else
		echo $var_name=$(eval echo \$$var_name)>> $conf_file	
	fi
}

function write_conf(){
	for var in $@ ; do
		write_conf_var "$var" "$CONF_FILE" 
	done
}

function read_conf(){ # $nom_var $default_val $conf_file
        local nom_var="$1"
        local default_val="$2"
        local conf_file="$3"

        if [[  -f "$conf_file" ]] &&  grep "^$nom_var=" "$conf_file" 2>&1 >/dev/null ; then
                eval $(grep "^$nom_var=" $conf_file)
        else
                eval $(echo $nom_var\=\"$default_val\")
        fi
        
}



function escape(){
        echo "$1" | sed "s/\,/\\\\,/g"  |  sed "s/(/\\\\(/g" | sed "s/)/\\\\)/g" | sed "s/\./\\./g"
}


function exists(){
        local ficonf="$1"
        local nomvar="$2"
 
	[ -f "$ficonf" ] && grep "${nomvar}=" "$ficonf" 2>&1 >/dev/null 
	return $? 
}

function writeConf(){
 	local ficonf="$1"
	local nomvar="$2"
 
	local valeur="$(eval echo \$${nomvar})"
	if exists "$ficonf" "$nomvar" ; then
		newfic="$(sed "s^${nomvar}=.*$^${nomvar}='${valeur}'^" "$ficonf")"
		echo "$newfic" > "$ficonf"	
	else
		echo "$(eval echo "$nomvar")='$valeur'" >> "$ficonf"
	fi 	
}
 
function readConf(){
        local ficonf="$1"
        local nomvar="$2"
	local default="$3"
 
	if exists "$ficonf" "$nomvar" ; then
		eval "$(grep "^${nomvar}=" "$ficonf")" 
        else
                eval "${nomvar}='${default}'" 
        fi   
}
function writeConfVars(){
        local ficonf="$1"
	shift
	for var in $@ ; do
		writeConf "$CONF_FILE" "$var"
	done
}

